version: '3.8'
services:
  magnet-index:
    image: magnet
    environment:
      MILVUS_HOST: ""
      MILVUS_PORT: "19530"
      MILVUS_USER: ""
      MILVUS_PASSWORD: ""
      DIMENSION: ""
      MODEL: ""
      INDEX: ""
      efConstruction: ""
      M: ""
      RESONATOR_URI: ""
      CATEGORY: ""
      SESSION: ""
      STREAM: ""
