version: '3'
services:
  app:
    build: .
    environment:
      - MAGNET_ROLE=index
      - HOST=""
      - STREAM_NAME=
      - CATEGORY=
      - KV_NAME=
      - SESSION=
      - OS_NAME=
      - MILVUS_URI=""
      - MILVUS_PORT=19530
      - MILVUS_USER=
      - MILVUS_PASSWORD=""
      - DIMENSION=1024
      - MODEL="BAAI/bge-large-en-v1.5"
      - INDEX_NAME=""
      - METRIC_TYPE=COSINE
      - INDEX_TYPE=HNSW
      - EF_CONSTRUCTION=40
      - M=48
    volumes:
      - ./:/app
    working_dir: /app