name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

permissions:
    contents: write
jobs:
  sphinx_docs_to_gh-pages:
    runs-on: macos-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.11
      - name: Installing the library
        run: |
          pip install sphinx sphinx_rtd_theme && pip install -r requirements.txt
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.1.0
        with:
          branch: main
          dir_docs: docs
          sphinxapiopts: '--separate -o .'
          sphinxapiexclude: '../*setup* ../*.ipynb'
          sphinxopts: ''